# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-22 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_thankyous'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatreonThankYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ThankYous',
        ),
    ]
