# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-06-22 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20200621_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patreonthankyou',
            name='created',
        ),
        migrations.RemoveField(
            model_name='patreonthankyou',
            name='modified',
        ),
        migrations.AddField(
            model_name='patreonthankyou',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patreonthankyou',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
